### ISSUE TITLE
Verify usability on Mac OS X

### ISSUE THREAD

**Issue by ecorm** [ecorm/cppwamp#9]
Verify that the library can be used and compiled on Mac OS X platforms.

**Comment by ecorm** [comment]
Fixed in #55.

**Comment by taion** [comment]
I just ported my actual project from AutobahnCpp to CppWAMP. Worked like a charm. Entirely straightforward given the existing docs.

There were a few minor glitches in the docs. I'll submit a PR for the ones in the project docs. One additional minor point - this Wiki page: https://github.com/ecorm/cppwamp/wiki/RPC#registering-statically-typed-procedures has the wrong `#include`, it should be `unpacker.hpp` rather than `unpacked.hpp`.

**Comment by ecorm** [comment]
Glad to hear the changeover went smoothly. I didn't have time to compile the documentation code snippets. Thanks for catching the wiki mistake; I'll fix it when I update the wiki for the revised API.
